language: python
python:
- '2.7'
- '3.3'
- pypy
services:
- docker
env:
  global:
  - secure: bhdCnWQmqaniXMHqKWm0wc0SWHvDxKy7BN9AyjVIp9EZqsO4UBALfk2Y0nAwnchpWqghs+QoJRGWZVOjAAaTO90cRQypRhEJRk5k36Y7R62/LrViV4GBy2jdIIvf3l+jU2HK9ZSp4WRI6miuQeDNLtXNXmjfEXQLS8J4T8tjrleUtxsFltFpq7YggigGgByZ+ExM8RA2n9fLDM/89bKq5gUqTHDPsYDsAANqdyJAV5IeE4MSz7u7NLpulcwiwQkTR8uJobUjmAsZascmtYHbHhRnLlCMup9Zu2hv7RPHajAWfodUT8w8RxAn54ehOBW4tvp66wNz8SZKPQ9ZXL3pbbekvzVybeWDfWJdIYqjzzI2MTcbjqv6FtzCCc+H7SMraGC+9uRwh794K9mgUeYKtAzFA5rA8T3Ydqdx4WGndubQrIBXIPcIbknz+OTkTJnHQ4FkGUh9qaW1VjZnMzyPpBa9XpGOnmzNYPf2x+XnApsnK18IBJPANl1rRKOL3VfPM9HgR5CWcOf2LXM55ST4xZxNwCdAXcyfv7K72bdHgizOL2gypylBcgRP7d1vLW3aWEWj7PJBe/yOdLoEa5ukhorQZpM6qfID9VsyTUUHQEy3NhO/4I5sL5RV4BjjmMVx6CrdCbZO5SVY3lExeJ5eqOAH7gozUXY/AiCn9PRggPw=
  - secure: Xm/R36/LcZr0hsVkiXWXkpoNMVbCKJiZ31GnjBqUMHi9MfDcQDQnLChWR+P3CTjsuc4Ff/3GIqPDJyHa5Rk1B3A1Wtw5iJtrx5uJzuU22uF6ggsmVyDWKW0n2iWf3X0B1WAAkdyaOsCHC51yh18XFIEGpi+qtqjSuEW7m/OcaZO3++CBA9eViHx7AeVpBE/IqXOnfxsW+I1vOxXBaLFPQifg+EA7HmkfjuH5zcj/j7aMeSeyzKSwVag8TwFazaSHpwrmylxyVGlFRg3gce2gDchP3RolZCdxQ1i+wMaDqrr4yINiJooO2S9nSm3PNW0oNQpFYkoVduocvFGcATA3S1m49vcLi+xZmUXonVIJtry1C1FQG8gmkIjUgy5jA7LBcloAXdACuo5Kyz4fH13cPYx9u/PPgCwdiFwq9SR1YhSn0xKxmB5cG3+aaaYy2+ffZworQIaYU/ON2REHFz3/FDtj9Xbya4ue3AvWNEsfVLI8SxOYhai18su+S/h32xg4UqsjHojlDVOnQVYIRIDrUKGp8V8uj60yZoeF7hSdeLtR16KRVETJwWpCsIZGn7cgMk8c0K+d+6pK/FSozIWfTENNU+ELRJuP8GIc7zBCV7pgrfvAo6XsWy5jeTFV7TRsuB1dSkrJAjBWL0j/fSZj8pgs9VrpGvjrgTsoj/FE+zI=
script:
- "./travis.sh"
