---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  log_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: log/xl-release-bot.log
    when: 'd'
    interval: 1
    backupCount: 30
    encoding: utf8

loggers:
  bot:
    level: INFO
    handlers: [console, log_file_handler]
    propagate: no

  bot.db:
    level: INFO
    handlers: [console, log_file_handler]
    propagate: no

  bot.slack:
    level: INFO
    handlers: [console, log_file_handler]
    propagate: no

  bot.helper:
    level: INFO
    handlers: [console, log_file_handler]
    propagate: no

  bot.dialogs:
    level: INFO
    handlers: [console, log_file_handler]
    propagate: no

  bot.messages:
    level: INFO
    handlers: [console, log_file_handler]
    propagate: no

  bot.xlrelease:
    level: INFO
    handlers: [console, log_file_handler]
    propagate: no

  bot.exceptions:
    level: INFO
    handlers: [console, log_file_handler]
    propagate: yes

root:
  level: INFO
  handlers: [console, log_file_handler]
