version: '2'

services:    
    consul:
        container_name: consul
        image: consul:latest
        ports:
            - "8500:8500"
            - "8300:8300"
        volumes:
            - ./config:/config
            - ./data/consul:/data
        command: agent -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1

    vault:
        container_name: vault
        image: vault
        links:
            - consul:consul
        depends_on:
            - consul
        ports:
            - "8200:8200"
        volumes_from:
            - consul
        cap_add:
            - IPC_LOCK
        command: server -config=/config/vault.hcl

    backup:
        container_name: backup
        build: backup/
        links:
            - consul:consul
        volumes:
            - ./data/backup:/backup/
        command: consul-backup
    
    redis:
        container_name: redis
        image: redis
        command: ["redis-server", "--appendonly", "yes"]
        ports: 
            - "6379:6379"
        volumes:
            - ./data/redis:/data
